---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sejutacita
spec:
  selector:
    matchLabels:
      app: sejutacita
  template:
    metadata:
      labels:
        app: sejutacita
    spec:
      containers:
        - name: sejutacita
          image: asia-southeast2-docker.pkg.dev/percobaan-gke/sejutacita/sejutacita:latest
          ports:
            - containerPort: 3000
              protocol: TCP