---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sejutacita
spec:
  selector:
    matchLabels:
      app: sejutacita
  template:
    metadata:
      labels:
        app: sejutacita
    spec:
      containers:
        - name: sejutacita
          image: ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/${{ secrets.REPOSITORY}}/${{ secrets.IMAGE}}:${{ secrets.TAG}}
          ports:
            - containerPort: 3000
              protocol: TCP