---
apiVersion: v1
kind: ConfigMap
metadata:
    name: sejutacita-config-map
data:
    # Port number
    PORT: "3000"

    # URL of the Mongo DB
    MONGODB_URL: "mongodb://sejutacitauser-user:sejutacitauser@34.101.200.188:27017/sejutacita?retryWrites=true&w=majority"
    